name: S3 Deploy
  # You may pin to the exact commit or the version.
  # uses: Reggionick/s3-deploy@d78e6b5a588e326e4b1afb9b33df2ce28929e5e1
  uses: Reggionick/s3-deploy@v3.1.0
  with:
    # Directory to deploy
    folder: photos
    # Name of AWS Bucket
    bucket: scottkingphotos-site
    # The destination bucket region
    bucket-region: ca-central-1
    # AWS CloudFront distribution ID
    dist-id: # optional
    # AWS CloudFront invalidation path(s)
    invalidation: # optional
    # Removes files in S3 that are not available in the local copy of the directory
    delete-removed: # optional
    # Use this parameter to specify Cache-Control: no-cache, no-store, must-revalidate header
    no-cache: # optional
    # Upload files with private ACL, needed for S3 static website hosting
    private: # optional
